/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Movie list Data
 */
export const MOVIE_LIST_DATA = [
  {
    'sort': 0,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_first'),
    'title': '消失的她',
    'describe': '本片改编自苏联电影《为单身汉设下的陷阱 Ловушка для одинокого мужчины》 ',
    'movieImage': $r('app.media.swiper1'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '何非（朱一龙 饰）的妻子李木子在结婚周年旅行中离奇消失，在何非苦寻无果之时妻子（文咏珊 饰）再次现身，何非却坚持眼前的陌生女人并非妻子，妻子拿出了身份证明进行自证，夫妻二人似乎都有不可告人的秘密，随着金牌律师陈麦（倪妮 饰）介入到这起离奇案件中，更多的谜团慢慢浮现…… '
  },
  {
    'sort': 1,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_second'),
    'title': '冲破黎明前的黑暗',
    'describe': '通过地道战的方式与日寇作斗争的故事',
    'movieImage': $r('app.media.ic_movie_two'),
    'cardImage': '/common/ic_movie_two.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '1剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 2,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_third'),
    'title': '党的女儿',
    'describe': '带领群众继续作斗争，最后壮烈牺牲的故事',
    'movieImage': $r('app.media.ic_movie_three'),
    'cardImage': '/common/ic_movie_three.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '2剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 3,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fourth'),
    'title': '古刹钟声',
    'describe': '抗日战争时期，八路军剿灭日本特务的故事',
    'movieImage': $r('app.media.ic_movie_four'),
    'cardImage': '/common/ic_movie_four.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_empty_star')],
    'rating': '9.0',
    'introduction': '3剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 4,
    'isShowSort': true,
    'sortImage': $r('app.media.ic_fifth'),
    'title': '花木兰',
    'describe': '花木兰替父从军，英姿飒爽的故事',
    'movieImage': $r('app.media.ic_movie_five'),
    'cardImage': '/common/ic_movie_five.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_empty_star')],
    'rating': '9.0',
    'introduction': '4剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 5,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '画中人',
    'describe': '讲述了一对相爱的年轻人，受到昏君的迫害，遇到仙人相助的故事',
    'movieImage': $r('app.media.ic_movie_six'),
    'cardImage': '/common/ic_movie_six.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '5剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 6,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '马兰花开',
    'describe': '讲述一位家庭妇女，为了参加新中国的建设，主动要学习驾驶推土机一系列故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '6剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 7,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '五朵金花',
    'describe': '讲述了大理地区，一对男女青年之间，产生了阴差阳错误会的爱情故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '7剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 8,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '战火中的青春',
    'describe': '讲述了解放战争期间，女扮男装高山参加解放军，成为副排长，与排长共同战斗的故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '8剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 9,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '祖国的花朵',
    'describe': '讲述了北京的一所小学，五年级的同学们先进帮后进的故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '9剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 10,
    'isShowSort': false,
    'sortImage': $r('app.media.ic_first'),
    'title': '冰上姐妹',
    'describe': '讲述冰上女运动员之间团结友爱，互帮互助的故事',
    'movieImage': $r('app.media.ic_movie_one'),
    'cardImage': '/common/ic_movie_one.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '10剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 11,
    'isShowSort': false,
    'sortImage': $r('app.media.ic_first'),
    'title': '长安三万里',
    'describe': '安史之乱爆发后数年，吐蕃大军攻打西南。大唐节度使高适交战不利，长安岌岌可危。',
    'movieImage': $r('app.media.ic_movie_eleven'),
    'cardImage': '/common/ic_movie_one.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '安史之乱爆发后数年，吐蕃大军攻打西南。大唐节度使高适交战不利，长安岌岌可危。困守孤城的高适向监军太监回忆起自己与李白的一生往事。 '
  },
];

export const FICTION_LIST_DATA = [
  {
    'sort': 5,
    'isShowSort': true,
    'sortImage': $r('app.media.icon'),
    'title': '画中人',
    'describe': '讲述了一对相爱的年轻人，受到昏君的迫害，遇到仙人相助的故事',
    'movieImage': $r('app.media.ic_movie_six'),
    'cardImage': '/common/ic_movie_six.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 6,
    'isShowSort': true,
    'sortImage': $r('app.media.icon'),
    'title': '马兰花开',
    'describe': '讲述一位家庭妇女，为了参加新中国的建设，主动要学习驾驶推土机一系列故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 7,
    'isShowSort': true,
    'sortImage': $r('app.media.icon'),
    'title': '五朵金花',
    'describe': '讲述了大理地区，一对男女青年之间，产生了阴差阳错误会的爱情故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 8,
    'isShowSort': true,
    'sortImage': $r('app.media.icon'),
    'title': '战火中的青春',
    'describe': '讲述了解放战争期间，女扮男装高山参加解放军，成为副排长，与排长共同战斗的故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 9,
    'isShowSort': true,
    'sortImage': $r('app.media.icon'),
    'title': '祖国的花朵',
    'describe': '讲述了北京的一所小学，五年级的同学们先进帮后进的故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  }
];

export const SWIPER_LIST_DATA = [
  {
    'sort': 11,
    'isShowSort': false,
    'sortImage': $r('app.media.ic_first'),
    'title': '长安三万里',
    'describe': '安史之乱爆发后数年，吐蕃大军攻打西南。大唐节度使高适交战不利，长安岌岌可危。',
    'movieImage': $r('app.media.ic_movie_eleven'),
    'cardImage': '/common/ic_movie_one.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star')],
    'rating': '9.5',
    'introduction': '安史之乱爆发后数年，吐蕃大军攻打西南。大唐节度使高适交战不利，长安岌岌可危。困守孤城的高适向监军太监回忆起自己与李白的一生往事。 '
  },
  {
    'sort': 6,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '马兰花开',
    'describe': '讲述一位家庭妇女，为了参加新中国的建设，主动要学习驾驶推土机一系列故事',
    'movieImage': $r('app.media.ic_movie_seven'),
    'cardImage': '/common/ic_movie_seven.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 7,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '五朵金花',
    'describe': '讲述了大理地区，一对男女青年之间，产生了阴差阳错误会的爱情故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },
  {
    'sort': 8,
    'isShowSort': false,
    'sortImage': $r('app.media.icon'),
    'title': '战火中的青春',
    'describe': '讲述了解放战争期间，女扮男装高山参加解放军，成为副排长，与排长共同战斗的故事',
    'movieImage': $r('app.media.ic_movie_eight'),
    'cardImage': '/common/ic_movie_eight.png',
    'stars': [$r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_star'), $r('app.media.ic_half_star'), $r('app.media.ic_empty_star')],
    'rating': '8.5',
    'introduction': '剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介。简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情简介剧情。'
  },

];
/**
 * Starring data
 */
export const STARRING_DATA: Resource[] = [
$r("app.media.ic_movie_one"),
$r("app.media.ic_movie_two"),
$r("app.media.ic_movie_three"),
$r("app.media.ic_movie_four"),
$r("app.media.ic_movie_five"),
$r("app.media.ic_movie_six")
];


/**
 * Stills data
 */
export const STILLS_DATA: Resource[] = [
$r("app.media.ic_movie_one"),
$r("app.media.ic_movie_seven"),
$r("app.media.ic_movie_eight"),
$r("app.media.ic_movie_three")
];
