/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Style constants for all features.
 */
export default class StyleConstants {
  /**
   * Common left the percentage of the 6.7.
   */
  static readonly COMMON_MARGIN_LEFT: string = '6.7%';

  /**
   * Details common margin size the percentage of the 1.5.
   */
  static readonly DETAILS_COMMON_MARGIN: string = '1.5%';

  /**
   * Column details width the percentage of the 93.4.
   */
  static readonly COLUMN_DETAILS_WIDTH: string = '93.4%';

  /**
   * Starring text width the percentage of the 76.6.
   */
  static readonly STARRING_TEXT_WIDTH: string = '76.6%';

  /**
   * Common margin top the percentage of the 3.2.
   */
  static readonly COMMON_MARGIN_TOP: string = '3.2%';

  /**
   * Common margin right the percentage of the 3.3.
   */
  static readonly COMMON_MARGIN_RIGHT: string = '3.3%';

  /**
   * Common margin bottom the percentage of the 1.
   */
  static readonly COMMON_MARGIN_BOTTOM: string = '1%';

  /**
   * Starring width the percentage of the 90.
   */
  static readonly STARRING_WIDTH: string = '90%';

  /**
   * Starring space of the 8.
   */
  static readonly STARRING_SPACE: number = 8;
  /**
   * Rstarring list width the percentage of the 93.3.
   */
  static readonly STARRING_LIST_WIDTH: string = '93.3%';

  /**
   * Rstarring list height the percentage of the 14.4.
   */
  static readonly STARRING_LIST_HEIGHT: string = '14.4%';

  /**
   * Stills text width the percentage of the 76.6.
   */
  static readonly STILLS_TEXT_WIDTH: string = '76.6%';

  /**
   * Stills width the percentage of the 90.
   */
  static readonly STILLS_WIDTH: string = '90%';

  static readonly SMALL_HEIGHT: string = '8%';

  static readonly BIG_HEIGHT: string = '100%';

  static readonly INPUT_ACCOUNT_LENGTH: number = 11;

  static readonly INPUT_LEFT: number = 10;

  static readonly INPUT_PADDING_LEFT: number = 2;
  static readonly LOGIN_LOGO_HEIGHT: string = '40%';

  /**
   *  Login bottom component height of the parent 60.
   */
  static readonly LOGIN_BOTTOM_HEIGHT: string = '60%';

  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT: string = '100%';

  /**
   * The width of button.
   */
  static readonly BUTTON_WIDTH: string = '90%';

  /**
   * Grid columns of the 4.
   */
  static readonly GRID_COLUMNS: string = '1fr 1fr 1fr 1fr';

  /**
   * Grid rows of two the 2.
   */
  static readonly GRID_ROWS: string = '1fr';

  /**
   * Home grid height of the parent 15.9.
   */
  static readonly HOME_GRID_HEIGHT: string = '8.5%';

  /**
   * Bar width lg of the parent 7.5.
   */
  static readonly BAR_WIDTH_LG: string = '7.5%' ;

  /**
   * Bar default height of the parent 7.2.
   */
  static readonly BAR_DEFAULT_HEIGHT: string = '7.2%';

  /**
   * Bar height lg of the parent 50.
   */
  static readonly BAR_HEIGHT_LG: string = '50%';

  /**
   * Component common width of the parent 95.
   */
  static readonly COMMON_WIDTH: string = '100%';

  /**
   * Input length of the account.
   */
  //static readonly INPUT_ACCOUNT_LENGTH: number = 11;

  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH: number = 8;

  /**
   *  Left padding of the input box.
   */
  //static readonly INPUT_PADDING_LEFT: number = 12;

  /**
   *  Layout weight of number 1.
   */
  static readonly WEIGHT_ONE: number = 1;

  /**
   * Common Spacing of Components.
   */
  static readonly COMMON_SPACE: number = 12;

  /**
   * Logo margin bottom of the parent 50.
   */
  static readonly LOGO_MARGIN_BOTTOM: number = 50;

  /**
   * Item space of the 12.
   */
  static readonly ITEM_SPACE: number = 12;

  /**
   * Grid aspect ratio of the 1.32.
   */
  static readonly GRID_ASPECT_RATIO: number = 1.32;

  /**
   * Swiper count of the 1.
   */
  static readonly SWIPER_COUNT_ONE: number = 1;

  /**
   * Swiper count of the 2.
   */
  static readonly SWIPER_COUNT_TWO: number = 2;

  /**
   * Swiper count of the 3.
   */
  static readonly SWIPER_COUNT_THREE: number = 3;

  /**
   * List column of the 2.
   */
  static readonly LIST_COLUMN_TWO: number = 2;

  /**
   * List column of the 3.
   */
  static readonly LIST_COLUMN_THREE: number = 3;

  /**
   * List column of the 4.
   */
  static readonly LIST_COLUMN_FOUR: number = 4;

  /**
   * Image list of the 12.
   */
  static readonly IMAGE_LIST_SPACE: number = 12;
  /**
   * Grid row columns sm of the 4.
   */
  static readonly COLUMNS_SM: number = 4;

  /**
   * Grid row columns md of the 8.
   */
  static readonly COLUMNS_MD: number = 8;

  /**
   * Grid row columns lg of the 12.
   */
  static readonly COLUMNS_LG: number = 12;

  /**
   * Grid gutter of the 12.
   */
  static readonly GRID_GUTTER: number = 12;

  /**
   * Grid col span sm of the 4.
   */
  static readonly SPAN_SM: number = 4;

  /**
   * Grid col span md of the 6.
   */
  static readonly SPAN_MD: number = 6;

  /**
   * Grid col span lg of the 8.
   */
  static readonly SPAN_LG: number = 8;

  /**
   * Grid col offset md of the 1.
   */
  static readonly OFFSET_MD: number = 1;

  /**
   * Grid col offset lg of the 2.
   */
  static readonly OFFSET_LG: number = 2;

  /**
   * Stills list space of the 4.
   */
  static readonly STILLS_LIST_SPACE: number = 4;

  /**
   * Stills list width the percentage of the 93.3.
   */
  static readonly STILLS_LIST_WIDTH: string = '93.3%';

  /**
   * List title margin the percentage of the 1.5.
   */
  static readonly LIST_TITLE_MARGIN: string = '1.5%';

  /**
   * List compoent space of the 12.
   */
  static readonly LIST_COMPONENT_SPACE: number = 12;

  /**
   * Item width the percentage of the 93.4.
   */
  static readonly ITEM_WIDTH: string = '93.4%';

  /**
   * Stars list space of the 3.
   */
  static readonly STARS_LIST_SPACE: number = 3;

  /**
   * Layout weight size of the 1.
   */
  //static readonly WEIGHT_ONE: number = 1;

  /**
   * Width the percentage of the 100.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Height the percentage of the 100.
   */
  static readonly FULL_HEIGHT: string = '100%';

}